apiVersion: v1
kind: Pod
metadata:
  name: pkad
spec:
  containers:
  - name: pkad
    image: poznajkubernetes/pkad:blue
    env:
    - name: ZMIENNA_1
      value: "Kocham"
    - name: ZMIENNA_2
      value: "K8s"
    resources: {}
