apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ["echo"]
    args: ["Narzędzie $(TOOLNAME), wersja $(VERSION)"]   
    env:
    - name: TOOLNAME
      value: "busybox"
    - name: VERSION 
      value: "latest"
    resources: {}