apiVersion: v1
kind: Pod
metadata:
  name: www-hp
  labels:
    name: www
spec:
  containers:
  - name: main
    image: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/html/
        name: repo-hostpath
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 80
  initContainers:
    - name: init
      image: poznajk8s/ubuntugit:v1
      command:
        - git
        - clone
        - "https://github.com/PoznajKubernetes/poznajkubernetes.github.io"
        - /repo_hostPath
      volumeMounts:
        - mountPath: /repo_hostPath
          name: repo-hostpath
  volumes:
  - name: repo-hostpath
    hostPath:
        path: /temp/git/