apiVersion: v1
kind: Pod
metadata:
  name: www-ed
  labels:
    name: www
spec:
  containers:
  - name: main
    image: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/html/index.html
        name: repo-emptydir
        subPath: index.html
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 80
  initContainers:
    - name: init
      image: poznajk8s/ubuntugit:v1
      command:
        - git
        - clone
        - "https://github.com/PoznajKubernetes/poznajkubernetes.github.io"
        - /repo_emptyDir/
      volumeMounts:
        - mountPath: /repo_emptyDir
          name: repo-emptydir
  volumes:
  - name: repo-emptydir
    emptyDir: {}