apiVersion: v1
kind: ConfigMap
metadata:
  name: subpath-overwrite-udhcpd
data:
  udhcpd.conf: "our new config"
---
apiVersion: v1
kind: Pod
metadata:
  name: subpath-overwrite-pod-udhcpd
  labels:
    name: subpath-overwrite-pod-udhcpd
spec:
  volumes:
  - name: cm
    configMap:
      name: subpath-overwrite-udhcpd
  containers:
  - name: subpath-overwrite-pod-pkad
    image: poznajkubernetes/pkad
    volumeMounts:
    - name: cm
      mountPath: /etc/udhcpd.conf
      subPath: udhcpd.conf
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
  restartPolicy: Never
