apiVersion: v1
kind: Pod
metadata:
  name: www
  labels:
    name: www
spec:
  containers:
  - name: main
    image: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: repo
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  initContainers:
    - name: init
      image: poznajk8s/ubuntugit:v1
      command:
        - git
        - clone
        - "https://github.com/PoznajKubernetes/poznajkubernetes.github.io"
        - /repo
      volumeMounts:
        - mountPath: /repo
          name: repo
  volumes:
  - name: repo
    emptyDir: {}
