apiVersion: v1
kind: Pod
metadata:
  name: multilabels1
  labels:
    app: helloapp
    instance: one
spec:
  containers:
  - name: multilabels1e1
    image: poznajkubernetes/helloapp:svc
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: multilabels2
  labels:
    app: helloapp
    instance: two
spec:
  containers:
  - name: multilabels2
    image: poznajkubernetes/helloapp:svc
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: node-multilabels
spec:
  type: NodePort
  selector:
    app: helloapp
  ports:
  - port: 8080
    name: http