apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    app: nginx
spec:
  initContainers:
    - name: pod-name
      image: busybox
      env:
        - name: POD_NAME
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
      command: ['sh', '-c', 'echo "Hello from $(POD_NAME)" > /work-dir/index.html']
      volumeMounts:
        - name: workdir
          mountPath: /work-dir
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: workdir
        mountPath: /usr/share/nginx/html
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
  volumes:
    - name: workdir
      emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: nginx
spec:
  initContainers:
    - name: pod-name
      image: busybox
      env:
        - name: POD_NAME
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
      command: ['sh', '-c', 'echo "Hello from $(POD_NAME)" > /work-dir/index.html']
      volumeMounts:
        - name: workdir
          mountPath: /work-dir
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: workdir
        mountPath: /usr/share/nginx/html
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
  volumes:
    - name: workdir
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http