apiVersion: v1
kind: Service
metadata:
  name: pkad-svc
  labels:
    app: pkad-ss
spec:
  ports:
  - port: 80
    name: nginx
  clusterIP: None
  selector:
    app: pkad-ss
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pkad-ss
spec:
  serviceName: pkad-ss
  selector:
    matchLabels:
      app: pkad-ss
  replicas: 2
  template:
    metadata:
      labels:
        app: pkad-ss
    spec:
      containers:
      - name: pkad-ss
        image: poznajkubernetes/pkad:blue
        resources: {}
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi