apiVersion: v1
kind: Pod
metadata:
  name: pkad-label-stg
  labels:
    app: ui
    env: stg
spec:
  terminationGracePeriodSeconds: 45
  containers:
  - name: pkad-label-stg
    image: poznajkubernetes/pkad
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
