apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-pv
  labels:
    volume: demo
spec:
  storageClassName: ""
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /temp/git/persistent_volume/retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-pvc
spec:
  storageClassName: ""
  selector:
    matchLabels:
      volume: demo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
  labels:
    name: www
spec:
  containers:
  - name: main
    image: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/html/
        name: repo
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 80
  initContainers:
    - name: init
      image: poznajk8s/ubuntugit:v1
      command:
        - git
        - clone
        - "https://github.com/PoznajKubernetes/poznajkubernetes.github.io"
        - /repo
      volumeMounts:
        - mountPath: /repo
          name: repo
  volumes:
  - name: repo
    persistentVolumeClaim:
        claimName: vol-pvc