apiVersion: v1
kind: Pod
metadata:
  name: pod-secret2
  labels:
    name: pod-secret2
spec:
  containers:
  - name: pod-secret2
    image: repo.treescale.com/login/poznajk8s/pkad:blue_cp
    envFrom:
      - secretRef:
          name: literal-sec
    volumeMounts:
      - mountPath: /secret/
        name: secret-volume
        readOnly: true
    resources: {}
    ports:
      - containerPort: 8080
  volumes:
    - name: secret-volume
      secret:
          secretName: file-sec
