apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  labels:
    name: pod-secret
spec:
  containers:
  - name: pod-secret
    image: repo.treescale.com/login/poznajk8s/pkad:blue_cp
    resources: {}
    ports:
      - containerPort: 8080
  imagePullSecrets:
    - name: treescalecred