apiVersion: v1
kind: Pod
metadata:
  name: additional-pod
  labels:
    tier: pkad-rs
spec:
  containers:
  - name: additional-pkad
    image: poznajkubernetes/pkad:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"