apiVersion: v1
kind: Pod
metadata:
  name: pod-cm3
spec:
  containers:
  - name: pod-cm3
    image: poznajkubernetes/pkad:blue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - configMapRef:
          name: cm3