apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    ns: demo
---
apiVersion: v1
kind: Pod
metadata:
  name: helloapp
  namespace: default
  labels:
    ns: default
spec:
  containers:
  - name: multilabels1e1
    image: poznajkubernetes/helloapp:svc
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: helloapp
  namespace: demo
  labels:
    ns: demo
spec:
  containers:
  - name: multilabels2
    image: poznajkubernetes/helloapp:svc
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: helloapp
  namespace: default
spec:
  type: ClusterIP
  selector:
    ns: default
  ports:
  - port: 8080
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: helloapp
  namespace: demo
spec:
  type: ClusterIP
  selector:
    ns: demo
  ports:
  - port: 8080
    name: http