apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkad
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pkad
  template:
    metadata:
      labels:
        app: pkad
    spec:
      containers:
      - name: pkad
        image: poznajkubernetes/pkad:blue
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: version
          value: v1
